/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    const val org_liquibase_gradle_gradle_plugin: String =
            "org.liquibase.gradle:org.liquibase.gradle.gradle.plugin:" +
            Versions.org_liquibase_gradle_gradle_plugin

    const val nu_studer_jooq_gradle_plugin: String =
            "nu.studer.jooq:nu.studer.jooq.gradle.plugin:" + Versions.nu_studer_jooq_gradle_plugin

    /**
     * https://logging.apache.org/log4j/2.x/
     */
    const val log4j_api: String = "org.apache.logging.log4j:log4j-api:" +
            Versions.org_apache_logging_log4j

    /**
     * https://logging.apache.org/log4j/2.x/
     */
    const val log4j_core: String = "org.apache.logging.log4j:log4j-core:" +
            Versions.org_apache_logging_log4j

    /**
     * https://logging.apache.org/log4j/2.x/
     */
    const val log4j_jcl: String = "org.apache.logging.log4j:log4j-jcl:" +
            Versions.org_apache_logging_log4j

    /**
     * https://logging.apache.org/log4j/2.x/
     */
    const val log4j_jul: String = "org.apache.logging.log4j:log4j-jul:" +
            Versions.org_apache_logging_log4j

    /**
     * https://logging.apache.org/log4j/2.x/
     */
    const val log4j_slf4j_impl: String = "org.apache.logging.log4j:log4j-slf4j-impl:" +
            Versions.org_apache_logging_log4j

    /**
     * https://github.com/FasterXML/jackson-modules-java8
     */
    const val jackson_datatype_jsr310: String =
            "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:" +
            Versions.jackson_datatype_jsr310

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.kotlinx_coroutines_core

    /**
     * https://github.com/FasterXML/jackson-module-kotlin
     */
    const val jackson_module_kotlin: String =
            "com.fasterxml.jackson.module:jackson-module-kotlin:" + Versions.jackson_module_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * http://github.com/FasterXML/jackson
     */
    const val jackson_annotations: String = "com.fasterxml.jackson.core:jackson-annotations:" +
            Versions.jackson_annotations

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
            Versions.org_junit_jupiter

    /**
     * http://jaxb.java.net
     */
    const val jaxb_core: String = "com.sun.xml.bind:jaxb-core:" + Versions.com_sun_xml_bind

    /**
     * https://javaee.github.io/jaxb-v2/
     */
    const val jaxb_impl: String = "com.sun.xml.bind:jaxb-impl:" + Versions.com_sun_xml_bind

    const val otj_pg_embedded: String = "com.opentable.components:otj-pg-embedded:" +
            Versions.otj_pg_embedded

    /**
     * http://www.liquibase.org
     */
    const val liquibase_core: String = "org.liquibase:liquibase-core:" + Versions.liquibase_core

    /**
     * http://commons.apache.org/proper/commons-lang/
     */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

    /**
     * http://assertj.org
     */
    const val assertj_core: String = "org.assertj:assertj-core:" + Versions.assertj_core

    /**
     * http://java.sun.com/javase/technologies/desktop/javabeans/jaf/index.jsp
     */
    const val activation: String = "javax.activation:activation:" + Versions.activation

    /**
     * https://github.com/pgjdbc/pgjdbc
     */
    const val postgresql: String = "org.postgresql:postgresql:" + Versions.postgresql

    /**
     * http://lmax-exchange.github.com/disruptor
     */
    const val disruptor: String = "com.lmax:disruptor:" + Versions.disruptor

    /**
     * https://github.com/brettwooldridge/HikariCP
     */
    const val hikaricp: String = "com.zaxxer:HikariCP:" + Versions.hikaricp

    /**
     * https://netty.io/
     */
    const val netty_transport_native_epoll: String = "io.netty:netty-transport-native-epoll:" +
            Versions.io_netty

    /**
     * https://netty.io/
     */
    const val netty_transport_native_unix_common: String =
            "io.netty:netty-transport-native-unix-common:" + Versions.io_netty

    /**
     * https://github.com/javaee/jaxb-spec
     */
    const val jaxb_api: String = "javax.xml.bind:jaxb-api:" + Versions.jaxb_api

    /**
     * http://www.jooq.org
     */
    const val jooq: String = "org.jooq:jooq:" + Versions.org_jooq

    /**
     * http://www.jooq.org
     */
    const val jooq_codegen: String = "org.jooq:jooq-codegen:" + Versions.org_jooq

    /**
     * http://www.jooq.org
     */
    const val jooq_meta: String = "org.jooq:jooq-meta:" + Versions.org_jooq

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_apache: String = "io.ktor:ktor-client-apache:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_jackson: String = "io.ktor:ktor-client-jackson:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_mock_jvm: String = "io.ktor:ktor-client-mock-jvm:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_jackson: String = "io.ktor:ktor-jackson:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_locations: String = "io.ktor:ktor-locations:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_server_core: String = "io.ktor:ktor-server-core:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_server_netty: String = "io.ktor:ktor-server-netty:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_server_test_host: String = "io.ktor:ktor-server-test-host:" + Versions.io_ktor

    /**
     * https://github.com/ajalt/clikt
     */
    const val clikt: String = "com.github.ajalt:clikt:" + Versions.clikt

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * https://github.com/google/gson
     */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson
}
