
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.6.3"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.3.50"

    const val de_undercouch_download_gradle_plugin: String = "4.0.0"

    const val org_liquibase_gradle_gradle_plugin: String = "2.0.1"

    const val com_github_marcoferrer_krotoplus: String = "0.5.0"

    const val com_moowork_node_gradle_plugin: String = "1.3.1"

    const val nu_studer_jooq_gradle_plugin: String = "3.0.3"

    const val kotlinx_coroutines_guava: String = "1.3.2"

    const val nebula_deb_gradle_plugin: String = "7.4.2"

    const val org_apache_logging_log4j: String = "2.12.1"

    const val jackson_datatype_jsr310: String = "2.9.9" // available: "2.10.0"

    const val kotlinx_coroutines_core: String = "1.3.2"

    const val commons_configuration2: String = "2.6"

    const val protobuf_gradle_plugin: String = "0.8.10"

    const val jackson_module_kotlin: String = "2.9.9" // available: "2.10.0"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val jackson_annotations: String = "2.9.9" // available: "2.10.0"

    const val org_junit_jupiter: String = "5.5.2"

    const val com_sun_xml_bind: String = "2.3.0.1"

    const val org_bouncycastle: String = "1.63"

    const val otj_pg_embedded: String = "0.13.2"

    const val dbsetup_kotlin: String = "2.1.0"

    const val liquibase_core: String = "3.8.0"

    const val assertj_core: String = "3.13.2"

    const val jaxb2_basics: String = "1.11.1"

    const val slf4j_simple: String = "1.7.28"

    const val htmlcleaner: String = "2.22" // available: "2.23"

    const val jaxws_tools: String = "2.3.2"

    const val owner_java8: String = "1.0.10"

    const val activation: String = "1.1.1"

    const val postgresql: String = "42.2.8"

    const val disruptor: String = "3.4.2"

    const val geoip_api: String = "1.3.1"

    const val atomicfu: String = "0.13.1"

    const val hikaricp: String = "3.4.1"

    const val io_netty: String = "4.1.38.Final" // available: "4.1.42.Final"

    const val jaxb_api: String = "2.3.1"

    const val org_jooq: String = "3.11.11"

    const val org_koin: String = "2.0.1"

    const val io_grpc: String = "1.24.0"

    const val io_ktor: String = "1.2.5"

    const val opencsv: String = "4.6"

    const val jsr305: String = "3.0.2"

    const val protoc: String = "3.9.0" // available: "3.10.0"

    const val mockk: String = "1.9.3"

    const val gson: String = "2.8.5"

    /**
     * Current version: "5.6.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
